
# stylua.toml — Stylua formatter settings for your Neovim config
# This file should live at ~/.config/nvim/stylua.toml

# Let Stylua treat this as the root of your project
root = true

# Maximum line width before wrapping
column_width = 100

# Use spaces (not tabs) for indentation
indent_type = "Spaces"
indent_width = 2

# Prefer double quotes unless single quotes are required
quote_style = "AutoPreferDouble"

# Ensure Unix-style line endings
line_endings = "Unix"

# How tables are formatted
table_separator = "Comma"

# Function call arguments formatting
function_call_args = "ForceMultiline"

# Control operator placement
align_args = true
align_parameters = true

# Wrap function call arguments when exceeding column_width
wrap_function_call_args = true
